/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Entidades.Lector;
import java.util.List;

/**
 *
 * @author giani
 */
public class ListaLectores extends javax.swing.JInternalFrame {

    javax.swing.table.DefaultTableModel modelTable = null;

    /**
     * Creates new form ListaLectores
     */
    public ListaLectores() {
        initComponents();
        String[] COLUMNAS = new String[]{"Nombre", "DNI", "Direccion", "Telefono", "Estado", "Fecha Nacimiento"};
        modelTable =  (javax.swing.table.DefaultTableModel)jTable2.getModel();
        modelTable.setColumnIdentifiers(COLUMNAS);
        iniciarTabla();
        
    }
        public void iniciarTabla(){
            int i=0;
            modelTable.setRowCount(0);
            BD.LectorData ld = new BD.LectorData(grupo1tpfinal.Grupo1TPFinal.CONEXION);
            List<Entidades.Lector> lista =ld.obtenerLectores();
            //modelTable.setRowCount(lista.size());
            for (Lector lector : lista) {    
                modelTable.insertRow(i, new String[]{lector.getNombre(),lector.getDni(),lector.getDireccion(),lector.getTelefono(),lector.getEstado()+"",lector.getFechaNacimiento()+""});
                i++;
            }
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable2.setModel(new javax.swing.table.DefaultTableModel());
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
